/**
 * 일일 브리핑 API
 * - GET: 저장된 브리핑 반환
 * - POST (body: {}): 서버사이드에서 Supabase 데이터 읽어 브리핑 자동 생성 + 저장
 */

import { NextRequest, NextResponse } from 'next/server';
import { getSession, isOwner } from '@/lib/auth';
import { getState, setState, getRecentEntries } from '@/lib/intelligence';

export async function GET() {
  const user = await getSession();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const brief = await getState('last_brief');
  return NextResponse.json({ brief, cached: true });
}

export async function POST(req: NextRequest) {
  const user = await getSession();
  if (!user || !isOwner(user)) return NextResponse.json({ error: 'Owner only' }, { status: 403 });

  const body = await req.json().catch(() => ({}));

  // 직접 브리핑 내용을 전달한 경우 (Claude Code 호환)
  if (body.summary || body.title) {
    const brief = { ...body, generatedAt: new Date().toISOString() };
    await setState('last_brief', brief);
    return NextResponse.json({ brief });
  }

  // 서버사이드 자동 생성: 최근 24시간 데이터 수집
  const [emails, slacks, calendars, memos] = await Promise.all([
    getRecentEntries('email', 24),
    getRecentEntries('slack', 24),
    getRecentEntries('calendar', 48),
    getRecentEntries('memo', 72),
  ]);

  const today = new Date().toLocaleDateString('ko-KR', {
    year: 'numeric', month: 'long', day: 'numeric', weekday: 'long',
  });

  // 이메일 요약
  const emailSummary = emails.slice(0, 5).map((e) => {
    const meta = e.metadata as Record<string, string>;
    return `• ${meta?.subject || e.content.substring(0, 60)} (${meta?.from?.split('<')[0]?.trim() || ''})`;
  }).join('\n') || '• 새 이메일 없음';

  // Slack 요약
  const slackSummary = slacks.slice(0, 5).map((s) => {
    const meta = s.metadata as Record<string, string>;
    return `• #${meta?.channel || '?'}: ${s.content.replace(/\[SLACK\][^|]+\|[^:]+: /, '').substring(0, 80)}`;
  }).join('\n') || '• 새 메시지 없음';

  // 캘린더 요약
  const calendarSummary = calendars.slice(0, 5).map((c) => {
    const meta = c.metadata as Record<string, string>;
    const start = meta?.start ? new Date(meta.start).toLocaleString('ko-KR', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : '';
    return `• ${meta?.title || '(제목 없음)'} ${start ? `— ${start}` : ''}`;
  }).join('\n') || '• 예정된 일정 없음';

  // 메모 요약
  const memoSummary = memos.slice(0, 3).map((m) => {
    return `• ${m.content.substring(0, 80)}`;
  }).join('\n') || '';

  const briefText = `📅 ${today} 브리핑

━━━ 📧 이메일 (최근 24h: ${emails.length}건) ━━━
${emailSummary}

━━━ 💬 Slack (최근 24h: ${slacks.length}건) ━━━
${slackSummary}

━━━ 📆 캘린더 (향후 48h: ${calendars.length}건) ━━━
${calendarSummary}
${memoSummary ? `\n━━━ 📝 최근 메모 ━━━\n${memoSummary}` : ''}

━━━ 📊 데이터 현황 ━━━
• 수집된 항목: 이메일 ${emails.length}건 · Slack ${slacks.length}건 · 캘린더 ${calendars.length}건
• 생성 시각: ${new Date().toLocaleString('ko-KR')}`;

  const brief = {
    title: `${today} 브리핑`,
    summary: briefText,
    emailCount: emails.length,
    slackCount: slacks.length,
    calendarCount: calendars.length,
    generatedAt: new Date().toISOString(),
    autoGenerated: true,
  };

  await setState('last_brief', brief);
  return NextResponse.json({ brief });
}
